### ISSUE TITLE
Избавиться от engine\config.classes.php (PSR-0)

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#1]
Избавиться от файла конфигурации ядра, в котором прописываются его классы. Сделать определение пути на класс ядра автоматическим по его namespace+ClassName в модуле Engine\Classes. Для этого потребуется переименовать/переместить некоторые классы ядра. Обратить внимание, что в  Engine\Classes имеются другие методы и сделать в них необходимые обновления.

**Comment by VladimirShestakov** [comment]
Предлагаю сделать полное соответствие namespace директории файла класса от корня сайта с точным соответствием регистра символов.

engine/databases/DB.php => 

``` PHP
namespace engine\databases;  
class DB {
...
}
```

**Comment by AzatGaliev** [comment]
Поддерживаю! Это называется PSR-0.

**Comment by VladimirShestakov** [comment]
Уточню. В [PSR-0](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md) есть особенность по поводу _ в имени класса - он заменяется на /. Для классов сайта это неприемлемо из-за свободы именования, хоть десять _ могут быть в нём.
Чтобы было единство, то и для классов ядра это исключение не стоит реализовывать. В PSR-0 есть ещё требования к регистру символов корневого namespace. 

В общем, не полное соответствие PSR-0 из-за архитектурных особенностей двига.

**Comment by AzatGaliev** [comment]
Я предлагаю сделать пока полный PSR-0 для ядра. Все объекты сайта оставить как есть. Над этим надо думать...

**Comment by VladimirShestakov** [comment]
Смысл? Изменения не ради соответствия стандарту, а для избавления от файла конфига, в первую очередь. Во-вторую очередь создание простого быстрого алгоритма определения путей. С полным PSR-0 потребуются различать, к чему относится класс, к ядру или нет и делать дополнительные преобразования. Задумайся, для чего лишние преобразования, если ядро не предполагается дополнять сторонним кодом, значимость стандарта нулевая. Более того, как уже сказано, для классов сайта его нельзя полностью реализовать. Поэтому незачем ради стандарта плодить исключения в коде. Главное избавиться от файла конфига ядра.

**Comment by AzatGaliev** [comment]
Никаких

> потребуются различать, к чему относится класс, к ядру или нет

не будет, пути будут вида 

`\boolive\Engine\Values
`

По-моему, тут понятно, что это класс контейнера опасных данных и относится он к ядру. Просто предлагаю сделать два корневых namespace'а - один для ядра, а второй для меняющихся в зависимости от пользователя данных (т.е. объектов сайта).

**Comment by AzatGaliev** [comment]
Ну а этот стандарт, ИМХО, для структурных целей + универсального загрузчика. Если в одной части системы будет он применен, а в другой нет - тут уже будет путаница.

**Comment by VladimirShestakov** [comment]
Речь про _ (Underscores) в имени класса

```
\namespace\package_name\Class_Name => /path/to/project/lib/vendor/namespace/package_name/Class/Name.php

```

**Comment by VladimirShestakov** [comment]
Я за PSR-0, но без 
Each "_" character in the CLASS NAME is converted to a   `DIRECTORY_SEPARATOR`.

**Comment by AzatGaliev** [comment]
Да бог с ним, пусть, даже и без него. Это же больше для загрузчика, если мы сделаем другой загрузчик, работать-то все равно по нашему будет =)

**Comment by VladimirShestakov** [comment]
Ну вот, я просто уточнял, что это не полный PSR-0 :)

**Comment by VladimirShestakov** [comment]
С корневым namespace надо ещё разобраться. Тут вопрос задевает классы сайта, а для них не хотелось бы иметь дополнительного namespace.
Класс ядра: `\engine\databases\DB => www/engine/databases/DB.php`
Класс сайта `\library\basic\my\My => www/site/library/basic/my/My.php`

Блин, чтоб не различать классы ядра и сайта, то сайту надо так тогда
Класс сайта `\site\library\basic\my\My => www/site/library/basic/my/My.php`

Но все равно без единого корневого namespace, так как свои модули/пакет должны располагаться в www/site/library/ или хотябы в www/site/ и смысла в корневом namespace не будет. Если в www/site/ и **не делать** namespace \site, то для своих модулей пользователь получит чистый namespace, например 
`\mycompany\widgets\x => www/site/mycompany/widgets/x.php`

**Comment by AzatGaliev** [comment]
А почему 

> не хотелось бы иметь дополнительного namespace.

?

**Comment by VladimirShestakov** [comment]
для чего он? Я показал на примере `\mycompany\widgets\x => www/site/mycompany/widgets/x.php`, что ему не нужны корневые namespace.

**Comment by AzatGaliev** [comment]
В принципе, согласен. Думаю, namespace'ы больше сделаны для неизменяемого кода, т.е. для ядра.

**Comment by VladimirShestakov** [comment]
Предлагаю для классов ядра сделать namespace начиная с `engine` в соответствии с директорией. `\engine\databases\DB => www/engine/databases/DB.php`. 

Чтобы упростить задачу определения путей для классов сайта всё-таки тоже делать namespace в соответствии с директорией, то есть начинать namespace с `site`. `\site\library\basic\my\My => www/site/library/basic/my/My.php`
 Так как сейчас для классов сайта не используется `namesapce site`, то придется это дело подправить) 

Таким образом, namespace ПОЛНОСТЬЮ совпадает с директорией файла класса от www/

Как думаешь? Нормально ли будет для своих классов всегда использовать `\site\..` ? :) В принципе, мы сразу понимаем для чего модуль пишется, для сайта или ядра

**Comment by AzatGaliev** [comment]
А я предлагаю все-таки задействовать корневой namespace `boolive`, который может соответствовать любой директории, в нашем случае, `www`. Устанавливаться это будет в загрузчике. Так будет более правильно =)

**Comment by AzatGaliev** [comment]
Ну на счет namespace'а сайта пока ничего не могу сказать, пока только до модели данных дошел, не полностью во всем разобрался =)

**Comment by VladimirShestakov** [comment]
Какая директория, www или не www для движка уже не имеет значения, это не его. Не нужно её связывать с кодом прописыванием в namespace. Зачем бессмысленно удлинять namesacе.

**Comment by AzatGaliev** [comment]
Дак это требование PSR-0, чтобы в названии namespace'а был `vendor_name`, т.е. название библиотеки.

**Comment by AzatGaliev** [comment]
> Each namespace must have a top-level namespace ("Vendor Name").

**Comment by VladimirShestakov** [comment]
engine переименовать в boolive

**Comment by AzatGaliev** [comment]
Ну или так =)

**Comment by AzatGaliev** [comment]
Суть еще в том, что корневой namespace может соответствовать абсолютно любой директории на диске. [Вот тут](http://xipp.wordpress.com/2012/02/14/%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F-%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%BE%D0%B2-%D0%B2-php-%D0%B8-psr-0/) на русском все подробно и понятно объяснено.

**Comment by AzatGaliev** [comment]
Т.е. `\boolive\Engine\Values` может соответствовать файлу `/home/www/public_html/engine/Values.php`

**Comment by AzatGaliev** [comment]
И задается это в автозагрузчике.

**Comment by VladimirShestakov** [comment]
По замыслу то понятно зачем namespace boolive, чтобы сделать глобально уникальное именование классам. Поэтому начинаю склоняться за его использование.

Смущает удлинение namespace везде)) И уже не скажешь, что namespace соответствует директории, нужно указывать дополнительно `\boolive`. А у разработчиков возникнет вопрос, почему им нужно в своем модуле писать boolive, если это `<vendor>`, и он должен соответствовать их компании.
Поэтому нет однозначного решения пока)

**Comment by AzatGaliev** [comment]
Дак в автозагрузчике сделать функцию, которая будет задавать соответствие `Vendor Name = Path`. Например,

```
Autoloader::registerVendor("myCompany", "/home/www-data/public_html/mycompany.ru/site/myCompany/");
```

**Comment by AzatGaliev** [comment]
Ну а по идее, смотря на другие framework'и/библиотеки, у них один root-namespace для ядра, а другой - для проекта. Т.е. для каждой компании свой Vendor - как-то неправильно =)

**Comment by VladimirShestakov** [comment]
Тогда правильней просто переименовать engine и не заниматься конфигами путей вендоров.

**Comment by VladimirShestakov** [comment]
Чтоб чётко по Namespace путь определять. Мне так больше нравится. Просто и понятно

**Comment by AzatGaliev** [comment]
мм, не совсем понял...

**Comment by VladimirShestakov** [comment]
`boolive\database\DB` вместо `engine\database\DB`
А для классов сайта не будет boolive, сохранится `site\...`

**Comment by AzatGaliev** [comment]
Ну я так и предполагал, что для сайта свой root-namespace =)

**Comment by VladimirShestakov** [comment]
Наконец решили как делать? :)

**Comment by VladimirShestakov** [comment]
А `<vendor>` с большой буквы писать надо.. директорию тоже получается надо назвать с большой буквы))

**Comment by AzatGaliev** [comment]
Ну, я думаю, сойдемся на этом =) Дело за реализацией.

> А с большой буквы писать надо.. директорию тоже получается надо назвать с большой буквы))

Ну, большинство серверов на Linux, так-что, придется, видимо, писать =) Либо namespace с маленькой.

**Comment by AzatGaliev** [comment]
И так, обобщим:
- root-namespace для ядра - `\Boolive`
- root-namespace для сайта - `\Site`
- Классы ядра имеют вид `\Boolive\Values\Values`
  - это соответствует файлу `/path/to/Boolive/Values/Values.php`
- Классы сайта имеют вид `\Site\library\...`
  - это соответствует файлу `/path/to/Site/library/....php`

**Comment by VladimirShestakov** [comment]
Да. И `/path/to/` определяется конфигом, обычно это корень web-директории.

**Comment by AzatGaliev** [comment]
Да, но, возможно, что ядро будет лежать не в корне web-директории, например, одно ядро на несколько проектов, поэтому надо предусмотреть такой вариант.

**Comment by VladimirShestakov** [comment]
Получается все равно нужно различать к чему относится класс, чтобы подставить путь соответствующий.

**Comment by AzatGaliev** [comment]
Ну да. Просто сам путь к ядру надо сделать необязательно в www-директории.

**Comment by AzatGaliev** [comment]
Ты не закрывай =) Не реализовали же в коде еще =)

**Comment by VladimirShestakov** [comment]
Я случайно не то нажал

**Comment by VladimirShestakov** [comment]
На сколько будет затратно определять, к чему относится класс? Что-то типа `if (substr($class, 0, 6) == 'Boolive')` и это делать при подключении каждого класса

**Comment by VladimirShestakov** [comment]
Возьмешься за реализацию?

**Comment by AzatGaliev** [comment]
Возьмусь =)

**Comment by AzatGaliev** [comment]
Да, это делать при подключении каждого класса. Только не `substr`, а сначала `$ns = explode("\", $class_name)`, а потом `if ($ns[0] == "Boolive") { /* code */ }`

**Comment by VladimirShestakov** [comment]
`if (substr($class, 0, 7) == 'Boolive\')`

**Comment by AzatGaliev** [comment]
Нет-нет.

```
$class_name = "\Boolive\Values\Values";
$ns = explore("\", $class_name); // массив из уровней namespace'а
    /*[0] = "Boolive"
      [1] = "Values"
      [2] = "Values"
    */
```

**Comment by VladimirShestakov** [comment]
Зачем?

**Comment by AzatGaliev** [comment]
Так проще, быстрее и в последующем этот массив все равно пригодится.

**Comment by AzatGaliev** [comment]
Хотя... Подумаю над этим, действительно, может и не надо.

**Comment by VladimirShestakov** [comment]
Подумай )

**Comment by AzatGaliev** [comment]
В принципе, все уже работает. Но пока мержить в develop не буду - надо потестить. Код в PSR-0.

**Comment by VladimirShestakov** [comment]
Отлично, вечером изучу

**Comment by VladimirShestakov** [comment]
Сделал полное обновление всех файлов (классов) сайта. В базе данных ещё нужно будет сделать обновления (в uri объектов тоже будем писать с Site/ как и namespace, чтобы не путаться). Жду от тебя сигнала готовности для слияния с веткой PSR-0. Я всё смержу и поправлю несоответствия.

**Comment by AzatGaliev** [comment]
Кстати, директорию переименовывать не надо было. У нас же ядро не Boolive, а engine, так что, и так бы работало =)

**Comment by AzatGaliev** [comment]
Ну, если еще и в URI дописывать, то там с большой буквы и надо чуть-чуть поправить MakeObject.

**Comment by AzatGaliev** [comment]
Ну, у меня все готово =) Можешь мержить.

**Comment by VladimirShestakov** [comment]
У меня появились сомнения по поводу namespace Boolive и Site :) Boolive - это всё вместе, а не только ядро системы. Необходимо различать именно модули ядра от модулей сайта, не вводя в заблуждения чем являются классы из Boolive. Ведь namespace Boolive говорит об авторстве (вендоре) классов, а не их особенностей. А у нас чёткое функционально различие между модулями ядра и модулями сайта, при этом наши модули (проекта Boolive) имеются в site.  Смысловая путаница получается... Поэтому склоняюсь вернуть namespace Engine.

По поводу Site рассуждения другие. У сайта имеется корневой объект, причем второй корневой не допускается по простой причине - всегда иметь объект, объединяющий собой ВСЕ объекты сайта. Чтобы в данных можно было сослаться на ВСЕ данные - на их корень. Это необходимость была проверена на экспериментальных решениях при построении интерфейса и структуры сайта. Но, допустим, мы используем namespace Site для всех классов сайта. По любому возникает мысль, а почему бы не сделать класс с другим корневым namespace и он будет вне папки site, т.е.образуется второй, третий корень. Это логично, и желание появится некоторые модули вынести из Site, например библиотеку можно было вынести из него. Но далее всё пойдет покругу, желание иметь корень на всё, сделаем корень, он заставит использовать корневой namespace, потом это вызовит размышления использовать другой корневой namespace... и т.д. по рекурсии. Необходимо просто убрать причины такого развития. Все модули сайта оставить в папке site, но не придумывать для них корневого Namespace, сделать так как уже сделано - корень имеет пустое имя.

Итак.
1. Вернуть namespace Engine для модулей ядра
2. Убрать namespace Site у модулей сайта.

В итоге PSR-0 движке мы не поддерживаем 100% и я не вижу аргументов полезных, чтоб его использовать. Почему? Если мы берем сторонний набор классов и размещаем его в директории сайта, то для них PSR-0 работает, так как классы могут иметь любые пространства имен, им не нужно иметь в корне Site!! Называй их как хочешь.

**Comment by VladimirShestakov** [comment]
Ядро переименовано в Boolive. Для классов сайта корневого namesapce нету. 
Делаю слияние и правки.

**Comment by AzatGaliev** [comment]
Все смержил в develop и удалил лишние ветки.
