### ISSUE TITLE
Пакет содержимого

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#10]
### Создать в библиотеке пакет с эталонами содержимого
- **Страница (статья) - page**
  - Заголовок - title
  - Текст - text
  - Описание - description
  - Автор - author
  - Ключевые слова - keywords
  - Оценки (голоса) - votes
  - Комментарии - comments
- **Раздел - part**
  - Заголовок - title
- **Обратная связь (форма) - feedback** 
  - Сообщение - message
  - От кого - email_from
  - Кому - email_to

Может, есть ещё часто используемые типы содержимого. Добавим сюда же. Всякие каталоги, товары, галереи, блоги - потом будут.  Насчет именования и местоположения пакета хз, не на раз реструктуризуем его ещё.
### Составные части содержимого

Для создания свойств (text, title) понадобятся эталоны более простых объектов 
#### Для текста
- Заголовок - head 
- Абзац - paragraph
- Картинка - image
- Таблица - table
- Список - list (ul/ol)
#### Для таблицы
- Строка - row
- Ячейка - cell
#### Для списка
- Пункт (элемент) - item
#### Ключевые слова
- tag
#### Комментарии
- comment
  - text
  - author
  - votes

Возможно, их нужно группировать в отдельные пакеты/подпакеты, например под названием "документ"
#### Эталоны ключевого слова, комментария, пользователя

В странице (статье) должны использоваться не эталоны автора, ключевого слова. Должны существовать разделы с конкретными ключевыми словами (справочник), должны быть реальные пользователи сайта сгруппированные. Вот в них используются эталоны пользователя, группы. А статье прототипируются конкретные ключевые слова/пользователи. 

Принцип работы ключевых слов, голосования и другого нужно ещё обдумывать. Но начать создавать эталоны необходимо, чтобы в деле обкатывать решения.

**Comment by paulinep** [comment]
Думаю для таблиц еще нужна сама таблица. Не будешь же создавать таблицу из отдельных строк и ячеек. Тем более что у таблицы могут быть заголовки.

**Comment by VladimirShestakov** [comment]
Нужна, но в эталонной таблицы не будет строк/ячеек ) Ну или по умолчанию одна строка на колонку.
Создание/редактирование/отображение таблицы - задача соответсвующего виджета - им обеспечивается удобство и все прелести для пользователя.

Подумать, тут нужно эталоны и для списка пустого, текста пустого, списка ключевых слов, оценок, комментов, что у статьи. (не самого коммента, а для commentS)

**Comment by paulinep** [comment]
Хотя вообще-то нет. Ты прав достаточно ячейки и м/б строки. Когда пользователь хочет таблицу у него достаточно спросить сколько он хочет строк и столбцов, и уже формировать от них объект таблицы. Насчет других эталонов наверное же не сложно совсем.

**Comment by paulinep** [comment]
разве все эти пустые эталоны это не простые файлы шаблонов?

**Comment by VladimirShestakov** [comment]
Это всё создать не сложно, так как не несёт за собой сложной логики. Просто предопределенная структура для повторного использование. Она нужна не только для повторного использования, ещё для классификации данных, то есть различать таблицу от не таблицы по принципу, что объект прототипирован от таблицы. А то, что у неё есть или нет колонок по умолчанию, это дело десятое и поправимое, если будет нужно. 

Сложности будут в создании виджетов, фактически программ, которые это дело должны отображать/редактировать, как настоящие программы-редакторы файлов.

**Comment by VladimirShestakov** [comment]
Это объекты содержимого, а не виджеты с шаблонами. Содержимое само себя не отображает.

**Comment by VladimirShestakov** [comment]
Заодно добавил подпакеты с эталонами простейших объектов (email, число), подпакет с пользователем и группой. Реструктуризовал существующие объекты, добавив подпакет для объектов интерфейса. Ну и по задачи подпакет для объектов содержимого. Пришлось обновить все сущесвтующие объекты и вне библиотеки, так как изменились пути на эталоны.
