### ISSUE TITLE
Прототипирование через ссылки

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#105]
Если объект A прототипирован от объекта B с признаком ссылки, то A не наследует свойства и логику B.  Наследуется объект, на которого ссылается B. Таким образом, объект-ссылка B используется для перенаправления наследования. 

Одно из применений - прототипирование объектов между разными сайтами, например, объект-ссылка B может находиться на сайте каталога (каталога модулей), когда как реальный эталон будет на сайте его автора. B будет на него ссылаться. Объекты каталога будут использоваться в качестве прокси

**Comment by paulinep** [comment]
Это наверное не очень хорошая ситуация, т.к. если объектом будет пользоваться большое число сайтов не приведет ли это к сильному увеличению нагрузки на сайт автора. Скорее надо чтобы объект находился в каталоге, а пользователи уже могут на него ссылаться.

**Comment by VladimirShestakov** [comment]
Прототипирование произойдет единожды, обращаться к сайту автора и каталогу нужно только за обновлениями.
