### ISSUE TITLE
Возможность разместить директорию ядра не в www-директории

### ISSUE THREAD

**Issue by AzatGaliev** [Boolive/Boolive#11]
Например, одно ядро на несколько проектов.

**Comment by VladimirShestakov** [comment]
Путь на ядро задаётся в константе config.php, тебе только надо различать класс ядра от сайта, чтоб соответствующую константу пути взять.

**Comment by AzatGaliev** [comment]
Да, но там путь относительно домена. А если я захочу ядро в корень ФС засунуть?

**Comment by VladimirShestakov** [comment]
Там два пути. Относительный и корневой

**Comment by VladimirShestakov** [comment]
DIR_WEB_ENGINE, DIR_SERVER_ENGINE
