### ISSUE TITLE
Сделать языковую локализацию через gettext

### ISSUE THREAD

**Issue by ghost** [Boolive/Boolive#113]
gettext — библиотека проекта GNU для интернационализации, широко применяемая в свободном ПО. Сделать языковую локализацию через gettext, что позволит ускорить процесс интернационализации движка, как  ВордПресс.

**Comment by VladimirShestakov** [comment]
Необходимо учитывать особенности двига. Практически все данные сильно детализированы на объекты. Объекты имеют привязку к языку. Модель данных спроектирована с учётом мультиязычности. Любое сообщение, виджет, статью можно представить в нескольких языках (они являются объектами). 

В программном коде, в шаблонах не должно быть данных, т.е. пользовательского текста. Где использовать gettext, если мы придерживаемся разделения данных и их представления? Модуль данных нам автоматически выдаст объекты с учётом указанного языка (локали). 

О чём стоит задуматься, так это об автоматическом переводе мелких объектов по словарю, чтобы не вынуждать себя раз за разом переводить одни и те же слова и сообщения. Для этого можно создать словарь (раздел в структуре данных) и объекты-сообщения из него использовать по ссылке в своих объектах-модулях, содержимом... Вот тут можно подумать об словарях gettext - их редактирования через админку и получения перевода (чтобы не импортировать словари в базу сайта).
