### ISSUE TITLE
Система кеширования - путь к производительности BooLive CMS...

### ISSUE THREAD

**Issue by ghost** [Boolive/Boolive#116]
Рано или поздно цмс будет расти в размерах, расширяться в плане функциональности... Поэтому часть данных, которые создаются динамически, нужно кешировать для увеличения производительности!
После, долгих размышлений... => мне кажется что Ваш Проджект очередной велосипед...не обижайтесь, но функционала недостающего на первых порах, например кеширование, усложняет задачу развития системы цмс в общем! Поэтому, пока Вы не залезли в дебри очередного повторения кода, который давно создан, рекомендую переписать Вам свой движок на какой-нить фреймворк, например ZendFramework, Symphony, YiiFramework...
Кстати, только не надо будет говорит, что фреймворки созданы с многими ненужными компонентами, которые не пригодятся вообще и будут снижать производительность... Все, что Вам нужно, Вы легко сможете оставить, а лишнее выкинуть.

**Comment by VladimirShestakov** [comment]
https://github.com/Boolive/Boolive/issues/83 Сначала обкатаем архитектуру двига, в первую очередь модель данных. Если методы кэширования не будут отличаться своей оригинальностью от существующих, возьмём существующие. Всё что нам нужно, мы легко можем взять, не привязывая себя к конкретному фреймворку, идеологии, архитектуре.

**Comment by ghost** [comment]
В чем заключается архитектура Вашего двига, модели данных? В чем заключается концепция ЦМС. C boolive.ru знаком, исчерпывающего материала не нашел! Разрешите это проблему, так как Вы главный разработчик.

**Comment by VladimirShestakov** [comment]
Прототипная модель данных. Всё является объектами. Сайт (проект) - это иерархия из объектов содержимого, интерфейса, пользователей и всего остального до мельчайших деталей, что вы сами можете придумать. Новые объекты создаются на основе существующих прототипированием их. При прототипировании наследуются значение объекта, логика и подчиненные объекты (свойства). Без лишних метаданных (типов, классов) получаем гибкую ничем не ограниченную структуру данных и логики. На ней формируются уникальные возможности повторного использования, создания любых данных прям из админки, разграничения доступа, связанности сайтов на уровне данных, а не html страниц, мультиязычности и персонализации данных и логики, гибкости интерфейса, масштабирования... Создаём гибкую систему для всех типов её пользователей.
