### ISSUE TITLE
Описание каждого файла-пхп цмс

### ISSUE THREAD

**Issue by ghost** [Boolive/Boolive#118]
Нужно сделать небольшое описание каждого файла цмс для понимания их работы, назначения, модели данных, логики...

**Comment by VladimirShestakov** [comment]
Небольшое описание пишется в самих файлах. Чтобы понять в целом работу системы и лучше ориентироваться по её функциями, нужно создавать документацию.

**Comment by VladimirShestakov** [comment]
#124
