### ISSUE TITLE
У всех констант путей (config.php) убрать слэш в конце.

### ISSUE THREAD

**Issue by AzatGaliev** [Boolive/Boolive#12]
Не будет путаницы и более наглядно, если пути будут иметь вид, например `$indexFile = DIR_WEB . '/' . 'index.php';`

**Comment by VladimirShestakov** [comment]
Это лишняя операция соединения строк. Путаницы не было с путями.

**Comment by AzatGaliev** [comment]
Есть путаница. Где-то в конце есть слэш, а где-то - нет. Пусть и лишняя, но наглядная.

**Comment by VladimirShestakov** [comment]
Из-за этих путей тебе придется править кучу файлов, тестировать всё. Если так важно изменение, то нужны существенные причины для смены.

**Comment by VladimirShestakov** [comment]
Если менять, то потребуется:
1. В самом config.php обновить функцию get_web_dir() чтоб без / возвращала. Ну и сами константы....
2. Везде, где применяются константы путей дописать /

Это, вроде, минимум, чтоб всё работало. Но подготовительные действия перед использованием констант выполняются с учетом наличия / на конце, поэтому потребуется в будущем убирать/менять лишние преобразования. Подумай, я не против смены путей, если последствия однозначно положительные :)
