### ISSUE TITLE
Детализация действий для контроля доступа

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#132]
На данный момент различаются три типа действий - чтение, запись и уничтожение объекта. При этом создание нового объекта, его редактирование и удаление в корзину попадает под действие запись. Т.е. нельзя запретить редактирование, разрешив создание объекта.

Появилась мысль сделать отдельные действии на изменения соответствующих атрибутов объекта - смена прототипа, смена родителя (перемещение), смена значения (редактирование), скрытие, удаление, переименование, загрузка файла, установка своего класса... Нужно ли столько действий?

**Comment by paulinep** [comment]
Нужно. наличие большего количества действий делает редактирование объекта более прозрачным для пользователя - он сможет осмысленно преобразовывать объекты. Кроме того, тут еще гибкость в назначении прав видна. Нужно только ужитывать трудоемкость такого разделения в реализации, ну и не будет ли наличие стольких действий тормозить работу движка

**Comment by VladimirShestakov** [comment]
Есть ещё проблема при создании нового объекта, если нет доступа на редактирование прототипа. Так как права доступа на прототип распространяются на всех его наследников, то получается, что доступа на редактирование не созданного наследника уже нет, т.е. его нельзя создать! 

Если различать действия создания и редактирования, то этой проблемы можно избежать.

**Comment by VladimirShestakov** [comment]
Доступ контролируется на следующие действия с объектом:
1. Чтение
2. Уничтожение
3. Запись
   1. Создание (использование в качестве прототипа)
   2. Изменение
      1. Добавление подчиненных (использование в качестве родителя)
      2. Изменение значения (само значение, по умолчанию, файл)
      3. Переименование
      4. Перемещение (смена родителя)
      5. Смена прототипа или его относительности
      6. Смена владельца, языка
      7. В черновик/опубликовать
      8. Скрыть/показать
      9. Связать/отвязать
      10. Своя/наследуемая логика
      11. Смена принадлежности
      12. Установка обновлений (смена признака diff на DIFF_NO)
4. Исполнение (вызов методов)
