### ISSUE TITLE
Создать виджет логотипа

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#15]
Виджет отображает фотографию. Фотография является свойством виджета и отображается им в виде ссылки на главную страницу сайта. Используются шаблоны, стили... Виджет сразу применить в интерфейсе сайта.

Возможно, создаётся на основе #24

**Comment by AzatGaliev** [comment]
Сделал виджет логотипа. /library/basic/interfaces/widgets/logo
