### ISSUE TITLE
Удаление закладки, созданной в админке?

### ISSUE THREAD

**Issue by yuri25** [Boolive/Boolive#157]
Сделал несколько закладок в админке слева в столбце... как их теперь удалить? Спасибо.

**Comment by VladimirShestakov** [comment]
Пока быстрой правки закладок нет, поэтому нужно перейти непосредственно к списку закладок по адресу `/Library/layouts/Admin/Bookmarks/object` и там удалять ненужные объекты-закладки

**Comment by VladimirShestakov** [comment]
Вопрос превращается в задачу. Необходимо по нажатию кнопочки (иконки) рядом с плюсиком добавления закладки активировать режим редактирования закладок. В этом режиме у всех закладок появляется крестик для удаления и возможность упорядочивать закладки перетаскиванием. 
И при добавлении закладки на объект автоматически находить для закладки родительскую закладку в соответствии с расположением объекта.

**Comment by VladimirShestakov** [comment]
Можно попробовать без дополнительной кнопочки и всегда у всех закладок показывать сбоку крестик. Чтобы работало как в браузерах - быстро создать закладку и быстро удалить.
