### ISSUE TITLE
Создать виджет Таблицы

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#29]
Виджет таблицы отображает объект таблицы без всяких средств редактирования.  Объект таблицы состоит из строк, в строках ячейки. В ячейках определены свойства размера и объединения (когд одна ячейка выступает в роли нескольких). Содержимое ячейки - это подчиенные объекты ячейки, ими могут быть любые объекты, поэтому отображение  ячейки должно быть таким же универсальным, как виджет содержимого. #17

**Comment by paulinep** [comment]
Там есть еще 1 коммит пересмотреный  a3ab2a4
