### ISSUE TITLE
Стиль кодирования

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#3]
Решаем, какой стиль кодирования использовать с обоснованием. И меняем его во всём коде.

**Comment by AzatGaliev** [comment]
Ну или PSR-1/2 (раз уж решились на PSR-0 =)))), либо Zend. Это мои предложения. В принципе, особой разницы нет, просто чтобы было едино все =) [Вот](http://habrahabr.ru/post/38214/) ссылка на список стандартов кодирования. А вот на [PSR-1](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md) и [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md).

**Comment by VladimirShestakov** [comment]
Согласен применить PSR-1 и PSR-2, он вроде не отличается от Zend (может в деталях). Правда, уже имеются исключения для классов сайта - их именовать можно по любому)) в текущем применяемом стиле

Отличия PSR от текущего стиля:
1. Открывающие скобки в объявлении класса и методов на новой отдельной строке
2. Отступы кода 4 пробелами вместо таба
3. elseif слитно. Сейчас раздельно с переносом if на новую строку, мне думалось раздельно более наглядно и стройно
4. Статические методы в нижнем регистр `methodName()`. Сейчас с большой буквы (не везде:))
5. use для каждого класса. Сейчас через запятую с переносами

Вроде всё.

**Comment by AzatGaliev** [comment]
Предлагаю `else if` оставить раздельным, но `if` на той же строке делать. Ну имя классов объектов сайта можно хоть как.

**Comment by VladimirShestakov** [comment]
По поводу use предлагаю экономней быть - писать один раз.

**Comment by AzatGaliev** [comment]
Ну можно так.

**Comment by VladimirShestakov** [comment]
Стиль именования:
Переменные и свойства `$var_name`, `$this->propety_name` 
Методы (включая статические методы и функции) `methodName()`
Константы `CONSTAN_NAME`
Классы `ClassName`. Для классов сайта допустим любой стиль, так как имя должно соответствовать объекту.

Именовать коротко, но со смыслом.

**Comment by AzatGaliev** [comment]
Предлагаю переменные тоже в camelCase.

**Comment by AzatGaliev** [comment]
Перед и после всех операторов - пробел. Ну кроме `$object->method()`, и логического отрицания `!$varName`.

**Comment by VladimirShestakov** [comment]
Переменные и свойства только $var_name, если не выражают собой имя метода (callback). Необходимо больше  визуальных отличий от методов и плавность восприятия переменой, без повышения акцента на части в имени переменной. В методах же этот способ ускоряет распознание действия и объекта, над которым (с которым) оно выполняется. Одинаковое именование усложняет работу мозгу, замедляет восприятие кода.

Про пробелы между операторами согласен.

**Comment by VladimirShestakov** [comment]
И да, именование всего должно быть кратким, но настолько, чтоб отражался необходимый смысл. В общем, не нужно лишних слов - кратко и по делу.
Вместо `$rootNamespaceArray` достаточно `$names` 

Да, остерегайся кодирования в имени типа значения. Важен смысл. Структура и источник значения переменной понятен из операций присвоения.
