### ISSUE TITLE
Создать виджет Списка

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#30]
Виджет списка отображает объект нумерованного и ненумерованного списка <ul> <ol>. Для отображения элементов списка использует отдельные виджеты, чтобы каждый элемент можно было отобразить уникально.

**Comment by AzatGaliev** [comment]
Провозились вместе с Владимиром, кое-как сделали =) Хозяйке на заметку: если у вас установлен xDebug, в php.ini установите опцию xdebug.max_nesting_level побольше (около 500, если начнутся ошибки про порог вложенности - поднимите еще).
