### ISSUE TITLE
Контроль доступа

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#31]
Спроектировать контроль доступа на выборку, изменение данных, исполнение... продумать, какие именно действия контролировать, как интегрировать проверку в модуль данных. Права устанавливаются на пользователя или группу пользователей, с учётом их иерархии. Если есть права у группы, то они применяются для пользователей этой группы и для подгрупп. 

Авторизацию пользователей и регистрацию в этой задачи не рассматривать, предполагать, что мы знаем, кто текущий пользователь и нужно контролировать его действия. 
1. Что собой представляет право доступа?
2. Как право назначается на группу/пользователя (это свойство пользователя или что-то иное?)
3. Нужны ли роли для объединения прав по смыслу?
4. Как учитываются права, где и как проверяется доступ? алгоритм.

**Comment by AzatGaliev** [comment]
Один из вариантов. Создать модуль ядра Auth. В нем реализовать методы получения информации о текущем пользователе, методы выхода, входа. Метод проверки доступа к определенному ресурсу (роли, задачи, операции) по имени, а также, по переданным пользовательским параметрам, которые используются в специальном необязательном выражении, которое исполняется при проверке права доступа (возвращает логический результат) и задается при создании роли (задачи, операции). Про место, где проверять, не думал.

**Comment by AzatGaliev** [comment]
Это так, черновик. Надо это хорошо продумывать, чтобы не переделывать по 100 раз.

**Comment by VladimirShestakov** [comment]
С модулем Auth согласен. У него должен быть метод, возвращающий текущего пользователя и методы входа (аутентификации) и выхода пользователя.  По остальному пока неопределенность. Вот думаю, какие виды действий необходимо контролировать. Ограничиться действием чтения и записи или делать неограниченный набор?

#### Право выполнить действие

Изначально можно вообще не говорить о неком праве и ролях, объединяющих множество прав. Дело в том, что проверку доступа можно реализовывать в классе конкретного пользователя или группы. Т.е. у пользователя сделать метод haveAccess() и в нём мы можем запрограммировать любое условие, хоть просто true возвращать, делая доступ на всё. Ну а далее смотреть, как запрограммировать общий для всех алгоритм, который настраивать можно было, например, дополнительными свойствами пользователя, связями с ролями...ит.д.

**Comment by AzatGaliev** [comment]
Думаю, необходимо создать отдельную ветку в корне, что-то вроде /Rights, ну и в ней многоуровневую структуру прав, ролей и т.д. Думаю, не стоит разделять роли, задачи и операции на отдельные группы, чтобы была возможность создать неограниченное кол-во уровней. Потом, в необходимую категорию помещаем объект, в качестве прототипа и которого - юзер или группа последних. Ну и метод проверки доступа реализовать непосредственно в модуле Auth, что-то вроде

``` php
if (Auth::checkAccess($user_object, $operation, $params)) {
    // code
} else {
    throw new AuthError(array('Вы не имеете прав на выполнение запрашиваемого действия'));
}
```

**Comment by VladimirShestakov** [comment]
Метод проверки в Auth, но непосредственно код проверки вряд ли в нём. Это как с шаблонизаторами... Т.е. из Auth должен вызываться код некого правила из предложенной тобой структуры /Rights. Но в Auth неизвестно, какие правила использовать. Известно только о текущем пользователе. Поэтому можно передавать проверку непосредственно пользователю или пытаться у пользователя найти свойство right, которое ссылается (прототипировано) на один из объект правила из /Rights.  В конечном счёте мы программируем сами права, где можем написать любую логику, любое условие... Например, можно будет полностью создать объект правила с оригинальным запрограммированным условием. Либо предоставить универсальный объект правила, которое можно настраивать без программирования - указывать на какой объект есть доступ чтения или записи...

**Comment by VladimirShestakov** [comment]
И да, раз правила представляют иерархию, то нужно исполнять не одно правило, а все подчиненные ещё. Может быть для правил не надо отдельных методов придумать, а пользоваться методом work() :)

**Comment by VladimirShestakov** [comment]
Самое же сложное, я считаю, это сохранить гибкость проверки доступа и сделать её максимально быстрой. Но ещё есть вопрос с проверкой доступа на объекты, которые ещё не выбраны из бд. Например, мы намереваемся выбрать 10 последних новостей с учётом контроля доступа. С текущим рассмотренным подходом проверять доступ мы будем уже на выбранные объекты. Но тогда выбрав 10 новостей в результате может оказаться их меньше 10. Довыбирать ещё не хватающие или же делать проверку на уровне условия выбора данных из базы?

**Comment by AzatGaliev** [comment]
Ну, это как я и говорю, что-то вроде пользовательского выражения. Думаю, в самом объекте задавать правило как-то не очень, а вдруг нам будет надо проверить определенное право у пользователя, которое не привязано ни к какому объекту?

**Comment by VladimirShestakov** [comment]
Уточни про какие объекты говоришь, а то ведь всё объекты

**Comment by AzatGaliev** [comment]
Нет, я просто не совсем правильно прочитал =) Так что, предыдущий комментарий не принимай во внимание.

**Comment by VladimirShestakov** [comment]
Необходимо понять, где именно инициируется проверка доступа (где она используется). С учётом детализации всего на простейшие объекты (сложные объекты - это композиция простейших) мы всё таки вынуждены оперировать простейшими общими действиями над ним - чтение, запись, может ещё исполнение. Потому что работая с конкретным объектом мы как бы не видим, в какой глобальной задачи он участвует. Он как клетка в организме. Совокупность же правил чтения и записи на разные объекты уже образуют высокоуровневое действие.

**Comment by AzatGaliev** [comment]
Ну что, надо что-то решать с контролем доступа. Я до завтра буду думать, там отпишусь, обсудим.

**Comment by AzatGaliev** [comment]
Ну, думаю вариант с отдельной веткой /Rights не очень привлекательный. Поэтому, предлагаю создать в прототипах юзера и группы юзеров подчиненного `rights`. Внутри него можно создавать подчиненных, которые будут являться правом (или "левом" =)) доступа к определенному объекту (объект определяется значением). У этого правила создать еще одного подчиненного, который значением будет определять степень доступа: 111 - полный доступ (чтение/запись/исполнение), 100 - только чтение, 110 - чтение и запись и т.д. Право "запись" предполагает изменение атрибутов у данного объекта и создание подчиненных. "чтение" - чтение атрибутов (выборка объекта) и выборка подчиненных, если на них не назначены ограничения. Непосредственно проверку встроить в класс `Boolive\data\Entity`, в методы `find()`, `findAll()`, `start()`, а также в метод `object()` класса `Boolive\data\Data`.

Все права иерархически наследуются. Т.е., если _Вася_ состоит в группе _Модераторы_, у которых есть возможность изменения любых комментариев, то и у _Васи_ есть такое право, если не указано иное.

Еще, как вариант, - задание прав доступа в самих объектах. Пока, вроде, все. Пиши, что думаешь.

**Comment by AzatGaliev** [comment]
Но тут появляется одна проблема: необходимо в правила добавлять логику. К примеру, _Вася_ имеет право изменять только свои записи. Но на уровне данных это никак не определить. Необходимо заложить какую-то логику, которая будет определять - если запись _Васи_, то - разрешать запись, нет - не разрешать.

**Comment by VladimirShestakov** [comment]
Ещё сам алгоритм проверки важно рассмотреть. Каким образом учитываются права в методах выборки/сохранения? От оптимальности проверки придется плясать) Ведь если всё учитывать, например права не только юзера, но и его группы, группы группы.. (иерархия), учитывать права установленные на эталоны юзеров/групп... там. Потом права уже на сами объекты, например, если на объект запрет доступа, то есть ли доступ на его подчиненных? Проверять многое нужно, что влияет на скорость.

**Comment by AzatGaliev** [comment]
Ну без иерархии, я думаю, никак. Как вариант, сделать какой-нибудь кэш, в него сохранять полный перечень прав определенного пользователя с учетом иерархии. И привязывать этот кэш к юзеру для более быстрой проверки.

Я думаю, стоит начать с написания аутентификации и выхода. Я за это и возьмусь. Сейчас еще подумаю, как это все примерно будет работать.

**Comment by AzatGaliev** [comment]
Наверное, отдельно права юзеров и права на объекты не стоит разделять. Либо то, либо это. Надо решить, права будут "у юзеров" или "на объекты". Соответственно, где эти самые права будут храниться.

**Comment by AzatGaliev** [comment]
На счет иерархии, в принципе, во многих классических CMS ведь тоже иерархия, и это не особо ударяет по производительности.

**Comment by VladimirShestakov** [comment]
`Пользователь <--->> Право <<---> Объект`

У нас иерархия пользователей и иерархия объектов. Их обе предполагается учитывать для гибкости. Кроме этого есть прототипирование, что тоже предполагается учитывать и в пользователях и в объектах. 
И тут возникает конкретный вопрос, как же их всех учитывать? Каков алгоритм проверки, как его оптимально реализовать и какая в итоге структура прав оптимальна - как представить право?

**Comment by VladimirShestakov** [comment]
О да, мы ведь ещё думали о группировки прав в роли) тогда и правах есть иерархия, что ещё усложняет. Хотя, последнее твое предложение сводится к не деланию ролей, что упрощает задачу.

**Comment by AzatGaliev** [comment]
Ну хорошо, можно учитывать в обе стороны. Алгоритм, наверное, надо уже на готовой системе аутентификации делать, а то получится абстрактно.

**Comment by VladimirShestakov** [comment]
Итак. Получить все права юзера с учетом прав его групп можно быстро, если применять кэширование. Тут вопрос с производительностью неактуален. Предположим мы имеем все права, хз в каком виде (в каком?), теперь их нужно как-то учитывать для выборки объектов. И именно здесь возникает сложнейший вопрос. По идеи проверку нужно внедрить в само условие выборки. Каким оно будет? Предполагаю слишком сложным.

**Comment by VladimirShestakov** [comment]
Когда мы пытаемся работать с конкретным объектом, нам достаточно проверить есть ли связь на него в правах юзера. Правда, необходимо учитывать не прямое соответствие uri в праве c uri проверяемого объекта, возможно, в праве указан uri его родителя или прототипа. Ну uri родителя элементарно сверить - оно в самом uri объекта есть)) а вот прототипы придется перебрать.

Такой вариант подойдет для проверки возможности записи, запуска объекта или когда выбирается конкретный объект.

Если выбираются объекты по условию, то возникает туча сложностей))

**Comment by AzatGaliev** [comment]
Ну с кэшем надо что-то придумать, и не только для этого конкретного случая. Ну вид прав я уже примерно описал, ты, вроде, не прокомментировал никак ([клац](https://github.com/Boolive/Boolive/issues/31#issuecomment-8812732)). Ну с выборкой давай подумаем. Для начала, необходимо проверить, можем ли мы читать объект, из которого мы выбираем. Ну тут понятно. Если да - читаем все. Далее, в отдельности проверяем каждый выбранный объект, можем ли мы его читать. Если да - отдаем пользователю, нет - так нет.

**Comment by AzatGaliev** [comment]
А если права нет - значит, доступ полный.

**Comment by VladimirShestakov** [comment]
Вид прав нормальный, в деталях, может, ещё поменять, чтобы подход к созданию был привычным (без кодов)

```
user
- rights // для группировки прав юзера
- - right1 // или по значению вид права, как предложил AzatGaliev (чтение/запись...), либо по прототипу различать
- - - object // ссылка на объект на который устанавливается право. А где ещё? ))
```

По идеи если прав нет, то доступа нет ) В целях безопасности нужно разрешать, а не запрещать.

**Comment by AzatGaliev** [comment]
Да, про object я забыл =)) Мне кажется, если прав нет, все-таки, лучше разрешать, так меньше объектов получится, т.к. большинство объектов доступно всем.

**Comment by VladimirShestakov** [comment]
Пойми сложности проверки при поиске. Мы сейчас в состоянии делать проверку только после выборки, но получается, что выбирая 10 объектов, в результате может оказаться меньше. Т.е. как получается - чтоб всё правильно было, нужно сначала выбрать все объекты (с учётом основного условия поиска), потом из результатов убрать объекты, на которые нет доступа. И уже после делать смещение и ограничение по количеству (LIMIT). Но мы не в состоянии будем выбрать 1000 объектов, чтоб оставить 10

**Comment by AzatGaliev** [comment]
Если по прототипам, то придется аж 9 прототипов делать. Как-то накладно... Можно просто сделать еще 3 подчиненных в праве: `read`, `write` и `exec`, а значением задать существование или отсутствия того или иного права.

**Comment by AzatGaliev** [comment]
Не понимаю, как влияет это на сложность поиска... В любом случае придется выбирать 1000 объектов, а потом оставлять только разрешенные.

**Comment by VladimirShestakov** [comment]
Мы не можем выбирать все объекты, памяти не хватит. Ты представляешь сайт с миллионом постов и чтобы отобразить на главной свежие 10 выбирать весь миллион и ещё по всему миллиону делать проверки контроля доступа?

**Comment by AzatGaliev** [comment]
Не, я не понимаю, как на это влияет поведение при отсутствии правила?

**Comment by VladimirShestakov** [comment]
Про отсутствие правила я не говорил, кроме утверждения, что если правил нет, то доступа нет по умолчанию

**Comment by AzatGaliev** [comment]
Ну вот мне это и ни понятно, по моему, проще по-умолчанию разрешать, так меньше правил получится, т.к. разрешений больше, чем запрещений.

**Comment by VladimirShestakov** [comment]
Что по умолчанию делать на алгоритм проверки не влияет, я предполагаю. Вопрос чисто в политике безопасности. Определимся с ней позже) Сейчас волнует, как именно проверка будет выполняться. Примерно уже понятно, но мы видим сложности проверки при поиске объектов.

Пока не приходит никакого решения на замену проверки после выборки. Придётся пробовать обновить алгоритм выборки так, чтобы в случаи постфильтра из-за контроля доступа, выбирать ещё часть данных, чтобы к результату добавить не хватающее кол-во. Например нам надо 10 новостей. Выбрали, к 3 доступа нет. Выбираем ещё 10 начиная с 11-ой. Из них берем первые 3 на которые есть доступ.
Подобный алгоритм, возможно, нужно реализовать в задаче  #52 (поиск по прототипу). А если реализовать задачу #46 (формат условия поиска) и суметь контроль доступа описывать условием поиска, то вся задача ложится на обработку условия поиска при его непосредственном выполнении.

**Comment by AzatGaliev** [comment]
Ну про добор значений я подумывал, но так и не сказал. Пока изучу эти
тикеты, если что-то придет в голову - напишу.

**Comment by AzatGaliev** [comment]
Хм, #46 - это же не формат условия поиска, а формат результата работы
контроллера?

**Comment by VladimirShestakov** [comment]
Перепутал, имел ввиду #7

**Comment by VladimirShestakov** [comment]
Рассмотрим условие поиска с учётом контроля доступа. 
1. У текущего пользователя выбираем все права на конкретный вид действия, например, чтение. Право - это связь на объект, к которому есть доступ. Фактически же получаем массив URI объектов, на которые имеем доступ. Выбор происходит с учётом прототипирования пользователей, а также выбираются права групп.

2.1. Нам нужно выбрать только те объекты, чьи URI есть в массиве. Но проверять нужно не только uri у объектов, но и их прототипы. 
2.2. Одновременно выбираются те объекты, чьи родители есть в нашем массиве. Фактически же проверяется uri выбираемых объектов по неполному совпадению (like), так как о всех родителях объекта известно по uri самого объекта.

В итоге получаем возможность определить право на конкретный объект, на "тип" объектов (по прототипу). Кроме того, определить право на объекты в зависимости от их расположения (по родителям). Такая же гибкость со стороны пользователей - можем назначать права для конкретного пользователя, групп пользователей, "типов" пользователей.

**Comment by VladimirShestakov** [comment]
А теперь рассмотрим вопрос совокупного учёта прав. 

Если по умолчанию НЕТ доступа ни на что, то наличие права разрешает доступ. Но стоит разрешить доступ на любой из объектов, так получаем полный доступ на ВСЕ его подчиненные, на всю его ветку. Тут же возникает необходимость запрещать доступ на конкретные подчиненные. В итоге нужно оперировать и "Правом" и "Запретом", учитывать, что кого перекрывает - это значительно усложняет условие доступа.

Если по умолчанию ЕСТЬ доступ на всё, то наличие права должно запрещать его (речь тогда не о праве, а о запрете). Запретив доступ на некий объект, мы не имеем доступа к его подчиненным, ко всей его ветке. Вроде логично и нет необходимости говорить об открытие доступа к одному из подчиненных. Этот вариант получается проще.

**Comment by VladimirShestakov** [comment]
Обдумал кое-что. В принципе получается всё хорошо, если по умолчанию доступ есть, а пользователю указывается запрет на что-то.

В эталоне пользователя делаем методы:
1. `checkAccess($action_kind, $object)` Возращает true/false - есть ли доступ на объект $object (можно указывать только его uri) чтобы совершить действие $action_kind (чтение, удаление, изменение, выполнение). Список действий жестко не ограничивается, так как по виду действия просто выбираются соответствующие правила. Мы их группируем по виду действия в самом пользователе.
2. `getAccessCond($action_kind)` возвращает готовое условие для выборки объектов. Это условие можно добавлять к основу условию выбора объектов. Используется в методах find(). Чтобы реализовать этот метод, необходимо сначала разобраться с задачей #7. 

В обоих методах происходит выборка своих "запретов", автоматом учитывается прототипирование пользователя, запреты выбираются и у родителей пользователя (его групп).

```
group1
- bans // группировка запретов
- - write // запреты записи
- - - page1 => "/Library/content_samples/Page"  // запрет записи всех страниц
- user1
- - bans
- - - write
- - - - all1 => "" //Запрет на запись во все объекты начиная с корневого
- - - - admin1 => "/Interface/html/body/admin" // запрет чтения интерфейса админки
- - - read
- - - - ...
```

Если текущий юзер `user1`, то получаем запреты на `/Library/content_samples/Page`, `{корень}`, `/Interface/html/body/admin`. После выполняем манипуляции с полученными uri - находим общую часть среди всех трёх - получаем `{корень}`. Если `{корень}` не было бы в запретах, то общей части бы не нашли и тогда остались бы и `/Library/content_samples/Page` и `/Interface/html/body/admin`. В общем, на этом этапе попытались удалить лишние запреты. 

В методе `checkAccess()` необходимо проверить, совпадает ли uri проверяемого объекта с одним из uri запрета? Если нет, то дополнительно проверяются прототипы объекта - их uri сверяются. Совпадения нашли, значит доступа нет.

В методе `getAccessCond()` нужно сформировать условие для поиска объектов, например `NOT (object.uri like "/Library/content_samples/Page%" OR object.uri like "/Interface/html/body/admin%" OR object IS "/Library/content_samples/Page" OR object IS "/Interface/html/body/admin"` Синтаксис условия выдуман, он не соответствует SQL, всё зависит от #7

Вот, получается весь контроль реализуется парой методов пользователя и что более интересно, у нас сохраняется возможность вместо общего алгоритма в конкретном пользователе до программировать что-то ещё специфичное. Другими словами у разработчиков есть возможность создать другого эталонного юзера с иной более продвинутой или наоборот упрощенной логикой проверки :)

**Comment by VladimirShestakov** [comment]
Вспомним про роли. Запреты пользователя группируются в `bans`, а роль - это и есть группировка запретов в нашем случаи. Можно не думать о ролях и просто добавлять поштучно запреты. Но есть возможность отдельно сформировать несколько `bans` и добавлять их к пользователям. Это будут роли. Что замечательно - имеем независимость алгоритма проверки от способа создания запретов. А за счёт прототипной модели данных имеем возможность дополнительно подстраивать роль у конкретного юзера. Заодно работает объединение ролей пользователя и его группы.

**Comment by VladimirShestakov** [comment]
Начну делать методы проверки доступа у юзеров и применение их при выборке объектов.

**Comment by VladimirShestakov** [comment]
Реализовано следующим образом.

У всех пользователей и групп есть подчиненный объект `access`, в нём имеются подчиненные, имена которых соответствуют виду действий, например `read`, `write`. Можно создавать любые виды действий. Типы этих объектов не принципиальны, так как просто группируют права. 
Внутри объектов видов действий добавляются непосредственно правила "доступа" или "запрета". Правило - это объект, прототипированный от того объекта, на которого определёно правило доступа/запрета. (ссылается на него). Значением объекта правила является целое число, определяющее вид правила
`1` - доступ на объект и всех его подчиненных
`2` - доступ только на подчиненных
`3` - доступ только на объект
`-1` - запрет на объект и всех его подчиненных
`-2` - запрет только на подчиненных
`-3` - запрет только на объект

Можно запретить доступ на всех подчиненных, а другим правилом разрешить доступ на конкретного подчиненного. 

Все права от пользователя, его групп и прототипов пользователя и групп объединяются! 

В классе Member реализован метод `getAccessCond()`, который возвращает условие доступа в формате условий поиска объектов #7. Возвращается оптимальное условие, например для поиска объектов в /Content в условии доступа не будут присутствовать лишние условия на другие разделы сайта. В том числе учитывается глубина условий.

Контроль доступа реализован для чтения объектов и их записи. Если нет доступа на чтение объекта, то возвращается экземпляр Entity (как при отсутствии объекта), в нём будет признак отсутствия доступа, нельзя будет получить истинные значения его атрибутов. При этом останется возможность обращаться к его подчиненным, так как к ним доступ может иметься.

**Comment by VladimirShestakov** [comment]
Дополнительная гибкость правил доступа будет достигнута при решении вопросов индексирования объектов. Необходимо определять доступ не только по иерархии объектов, но и по их прототипам. Если нет доступа на эталон страниц, то не должно быть доступа ко всем страницам и их подчиненным.

**Comment by VladimirShestakov** [comment]
Алгоритм контроля изменен. Теперь в пользователе или в группе пользователей имеется свойство access, внутрь которого добавляются роли - объекты, прототипированные от `/Library/access/Role`. 

В объекте роли имеются подчиненные `read` и `write` - это действия, для которых далее определяются условия доступа. Можно добавлять свои действия. 

Проверка наличия доступа у пользователя что-то сделать с объектом:

``` php
if ($user->checkAccess('action_name', $object){
   /// 
}
```

Доступ на чтение и запись автоматически учитывается в модуле данных.

В объекты действий добавляются условия доступа - объекты прототипированные от `/Library/access/Allow` или `/Library/access/Deny`, соответственно, разрешающие или запрещающие доступ. На что именно имеется разрешение или запрет добавляется уже в них. В объекты-условия доступа можно добавить любое кол-во объектов. 

Если в Deny добавить `/Library/content_samples/Page`, то будет запрет доступа на указанный объект, а также всех его свойств и наследников, т.е. на все страницы сайта. В том числе и на свойства страниц. 

Условия доступа имеют приоритет в зависимости от своей очередности. На приоритет также влияет очередность ролей и группировка пользователей, таким образом, условие в пользователе будет накладываться на условие групп. Если запретить доступ к каталогу а потом разрешить доступ к подкаталогу, то будет доступ к подкаталогу. Если сначала разрешить, а потом запретить, то доступа не будет.

На данный момент созданы простейшие условия - запрет и доступ. Они являются объектами со своей логикой, а точнее методом getAccessCond(). Этот метод возвращает условие в формате как условие поиска объектов. Можно создавать дополнительные объекты для условий доступа, например, условие авторства. В условии доступа можно написать всё, что можно писать для поиска объектов.
