### ISSUE TITLE
Создать виджет навигации "Следующая и предыдущая страницы"

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#36]
Виджетом отображаются ссылки на предыдущую страницу и следующую с учётом иерархии страниц. Виджет оперирует объектом из входящих данных, если он является страницей. Если не является, то виджет не должен работать.

**Comment by AzatGaliev** [comment]
Сделал базовую версию - бегает по страницам вперед назад, не учитывая иерархию. Осталось добавить поддержку не только страниц (поддержка задания прототипов того, что можно отображать) и поддержку иерархии.

**Comment by VladimirShestakov** [comment]
При составлении условий поиска применяй плейсхолдеры:

```
$next = $object->parent()->find(array(
    'where' => '`order` > ? and `proto` = ?',
    'values' => array($object['order'], '/Library/content_samples/Page'),
    'count' => 1,
    'order' => '`order` ASC',
));
```

**Comment by AzatGaliev** [comment]
Понял, спасибо, учту

**Comment by AzatGaliev** [comment]
Блин, я так placeholder'ы и не добавил... Ладно. Этот issue закрываю, позже создам другой, когда будем делать поиск и хождение по дереву.
