### ISSUE TITLE
Подсчёт количества объектов

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#37]
Как определять количество объектов по определенному условию? С первого раза ответ очевидный - сделать `SELECT count(*) FROM ...`  В WHERE будет соответствующее условие на uri, если необходимо определить количество подчиненных. Могут быть и другие условия. Пока всё просто.

Но стоит только задуматься об учете наследуемых подчиненных объектов, так сразу становится всё оочень сложно) Дело в том, что подсчёт количества сводится не к суммированию количества своих подчиненных и подчиненных прототипа. Необходимо учитывать переопределяемые подчиненных, то есть не считать их. Например у объект есть подчиненный `title` и с таким же именем есть подчиненный у прототипа. В итоге считается, что `title` переопределяется (или наследуется) и общее кол-во подчиненных равно 1 (если других нет).

Так вот, как же эффективней (быстро и без затрат на память) выполнять подсчёт?

**Comment by AzatGaliev** [comment]
Сделать запрос по своим подчиненным, только кроме `count(*)` выбрать еще URI, по нему определим имя, и потом сделаем запрос по подчиненным прототипа, `WHERE uri NOT IN (*)`

**Comment by VladimirShestakov** [comment]
Пока подчиненных мало, проканает. А если их 100000? Например товар в каталоге, а посчитать его надо, чтоб постраничную навигацию сделать.

**Comment by VladimirShestakov** [comment]
Ещё один вариант основанный на кэшировании объектов. Кэш может представлять из себя полную копию всей базы данных. 

Главная особенность - в кэше должны быть и виртуальные объекты. Виртуальные объекты нужно кэшировать, так как движок всё равно пытается сначала проверить их наличие в БД. 

Если в кэш будут и виртуальные объекты, то при выборе из него не нужно учитывать прототипирование. Если в нормальной базе у объекта может не быть своих подчиненных из-за наследования подчиненных прототипа, то в кэше объект будет иметь те самые унаследованные виртуальные подчиненные.

В итоге легко посчитать их количество.

**Comment by VladimirShestakov** [comment]
Подсчёт возможен, если поиск работает по индексу #65. В условии поиска необходимо указать подсчёт объектов.

``` php
$cond = array(
    'select' => "count",   // Указывается, если нужно количество, а не объекты
    'from' => array('/Interfaces', 3),   // выбор объектов из /Interfaces в глубину до 3 уровней
    'where' => array(    // услвоия выборки        
    )
);
```
