### ISSUE TITLE
Содержимое директории Site вынести в www? 

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#39]
Задаюсь вопросом о возможности переноса всех подпапок из Site в www, чтобы чуток уменьшить вложенность Site? Таким образом в www будет Boolive, Contents, Interfaces, Library, Members, Keywords... Кстати, избавимся от особенности namespace для классов сайта - они тоже станут в точности соответствовать директории.

**Comment by paulinep** [comment]
Если  namespace станут точно соответствовать директории, то конечно надо переносить.

**Comment by VladimirShestakov** [comment]
Ну это косвенный плюс, хоть и значимый) Изначально задумался о вложенности, уж больно много папок, подпапок, теряешься в них

**Comment by VladimirShestakov** [comment]
В папке Site есть ещё класс Site.php - это логика корневого объекта. После переноса этот класс будет в www, рядом с файлом index.php  и конфигами. Нормально?

**Comment by paulinep** [comment]
Я думаю, что  еще один файл рядом с index это не страшно.

**Comment by VladimirShestakov** [comment]
![dirs](http://boolive.ru/wp-content/uploads/2012/08/new_dirs.png)

**Comment by VladimirShestakov** [comment]
Хм. С такой структурой новые размышления появляются по архитектуре ядра. Например, не передавать управление ядру (Engine) в index.php, а просто подключить его, чтоб загрузка некоторых модулей выполнилась. В обще, ядром можно счиатть сам файл index.php (микроядро), он подключает автозагрузчик из Boolive, получает корневой объект Site и исполняет его. А Engine можно объеденить с Classes, назвав их Boolive - его функции: автоазгрузка классов по требованию и вызов событий START/STOP, которые сейчас Engine вызывает.

**Comment by VladimirShestakov** [comment]
index.php

```
<?php
use Boolive\Boolive,
    Boolive\data\Data,
    Boolive\commands\Commands,
    Boolive\input\Input;

// Подключение базовой конфигурации проекта
require 'config.php';

// Подключение и активация движка Boolive
require DIR_SERVER_ENGINE.'Boolive.php';
Boolive::activate();

// Исполнение корневого объекта сайта и вывод результата
echo Data::object('')->start(new Commands(), Input::getSource());

```
