### ISSUE TITLE
Вести файл CHANGESLOG

### ISSUE THREAD

**Issue by AzatGaliev** [Boolive/Boolive#4]
Предлагаю создать и вести файл CHANGESLOG. Формат можно обговорить. Ну и, может быть, коммиты делать на русском? Или не надо?

**Comment by VladimirShestakov** [comment]
Расскажи как с ним работать. Комиты можешь на русском, но в планах сделать проект для англоязычной аудитории, поэтому практикуюсь.

**Comment by AzatGaliev** [comment]
А, ну раз на англоязычную аудиторию рассчитываешь, то тогда оставим как есть. Расскажу чуть попозже. Через пару часиков.

**Comment by VladimirShestakov** [comment]
Его создать, там где общий README
Формат

```
Boolive Change Log
============

Version 2.0-preview work in progress
----------------------------------
- bug #991: comment (user_name)
- enh #999, enh #998: comment (user_name)
- new #989: comment (user_name)
- chg #985: comment (user_name)

Version 1.0 September 17, 2010
----------------------------------
- bug #199: comment (user_name)
- enh #159: comment (user_name)
- chg #150: comment (user_name)
```

`- Тип issue #Код issue: Короткое описание (имя пользователя на github)`
bug - Ошибка
new - Новая функция/возможность
enhancement - Улучшение существующего
change - Какое-то нейтральное изменение
... и другие теги из списка Issues
