### ISSUE TITLE
Подключение CSS и JS (автоматическое)

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#42]
С текущим способом подключения css и js нарушается последовательность их вставки в html. Связано это с разным способ исполнения подчиненных виджетов - непосредственно в логике виджета в методе work и из шаблона. Если подчиненные виджеты исполняются из шаблона (простым обращением к ним), то сначала подключается стиль родителя. Но если виджеты исполняются в логике, то сперва подключаются их стили, а потом стиль родителя, так как родитель будет выполнять свою шаблонизацию после исполнения подчиненных.
Из-за этого невозможно обеспечить правильную (нужную) последовательность подключения стилей, так как применяются оба варианта исполнения подчиненных. 

Вместо урезания возможностей системы, необходимо реализовать третий автоматический способ подключения стилей и скриптов, и использовать его по умолчанию.

Эталонному виджету `/Library/basic/widgets/Widget` добавить подчиненного `res` (ресурсы) прототипируя его от `/Library/basic/Group` и всегда исполнять его перед шаблонизацией. 

Это позволит для любого виджета просто добавлять необходимые стили и скрипты к `res` не редактируя ни шаблон ни логику. Но самое главное - получим правильную последовательность подключения.

Возможность "ручного" подключения стиля не отменяется.

**Comment by VladimirShestakov** [comment]
Вместо "name" используй "title", чтобы единообразно со всеми объектами было (в .info)
Ещё необходимо в самом виджете в его методе work перед шаблонизацией исполнять res

**Comment by AzatGaliev** [comment]
Понял, прости, сейчас исправимся =)
