### ISSUE TITLE
Наследование классов и прототипирование

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#47]
Если объект B прототипирован от объекта A, то кроме свойств объекта наследуется и его логика. Логика объекта описывается классом, поэтому получаем класс B наследованного от класса A. 

```
class B extends A{}
```

Всё просто)

Но, допустим, объекту B не понадобилось делать своей логики, поэтому класс для него не создавался. Для объекта B будет использован класс объекта A. Речь идет об объектах модели данных (они в БД), при выполнении программы объект B на самом деле окажется экземпляром класс A.

Пока всё в прядке.

Теперь рассмотрим появление третьего объекта - C, прототипированием B. Объекту C нужна своя логика (дополнения), поэтому создаётся класс для него. Так как прототипируется объект B, то следовало бы наследовать его класс, но у него класса нет, поэтому наследуется класс A. 

Результат рабочий, пока всё верно.

Но вдруг решается, что объекту B тоже потребовалась своя логика - необходимость создать класс для него. Класс наследуется от A, но теперь возникает вопрос, что делать со всеми объектами, прототипирующие B? Ведь их классы необходимо тоже обновлять, меняя `extends` на B. !!

Проблема в жесткой связанности на уровне программного кода, что препятствует легкому добавлению логики объекту.

Возможное решение:

Не использовать наследование классов. Вместо наследования применять обращение к прототипу. Например, когда переопределяется логика прототипа, то вместо `parent::method()` использовать `$this->proto()->method();` Кроме этого, в магическом методе `__call($method_name, $arg)` реализовать обращение к соответсвующему методу прототипа. Таким образом, если вызывается несуществующий метод, то вызов адресуется прототипу. Но кроме наследования методов, придется ещё как-то имитировать наследование внутренних свойств. 

)) Ощущение, что на PHP пытаемся программировать как на JS ))

**Comment by VladimirShestakov** [comment]
```
<?php
/**
 * Логика для какого-то баннера) пример
 * @version 1.0
 */
namespace Interfaces\html\body\sidebar\banner;

class logic
{
    protected function work($v = array())
    {
        $v['title'] = "Нечто иное, чем по умолчанию";
        return $this->proto()->work($v);  // вместо parent::work($v);
    }
}

```

Как-то так. Именование класса уже не имеет значения, кстати, так как есть namespace

**Comment by VladimirShestakov** [comment]
Плохо то, что по коду не будет понятно, что наследуется.. где смотреть логику наследуемого класса (объекта). IDE меньше подсказок будет делать.

**Comment by AzatGaliev** [comment]
А Entity разве не надо наследовать? Еще один выход - создавать классы абсолютно для всех объектов (для всех View), если нет логики - то делать их пустыми. Тогда + ко всему отпадет необходимость в свойстве is_logic, ведь так? С IDE без подсказок - да, не хорошо...

**Comment by VladimirShestakov** [comment]
Каждой странице, тексту, абзацу, каждому комментарию тогда потребуется создавать класс. Ведь проблема общая, не только для View. (виджетов).

**Comment by VladimirShestakov** [comment]
Предложенное мною решение хреновое))..по поводу вызова прототипов. Так как вызов прототипа - это обращение к другому объекту, и часто повторное, в котором недоступен контекст вызывающего объекта. Что собственно не может имитировать наследование.

Делать всему классы логически верное, но по поводу оптимальности...эмм
