### ISSUE TITLE
Создать обработчик напрвленных запросов - DirectHandler

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#55]
Если в запросе имеется параметр POST['view'] или GET['view'], то исполняется объект, чей uri в view. Прямая обработка запроса необходима для обновления виджетов со стороны клиента без полной перегрузки страницы. 

Необходимо создать объект-обработчик запросов DirectHandler, поместить его в /Interfaces, чтобы работал при наличии POST['view'] или GET['view'] с uri существующего объекта. DirectHandler обычно будет исполнять виджеты, которые взвращают результат в HTML, в $command указывают, какие стили и скрипты они хотят подключить. DirectHandler формирует результат в JSON, в который заносится результат виджетов (HTML) и список путей на стили и скрипты.

Со стороны клиента останется вставить полученный html в соответствующую область и подключить новые стили и скрипты к DOM.

DirectHandler всегда возвращает результат в JSON, при этом запускаемый виджет может возвращать не только HTML (строку), но и любые другие данные, которые в итоге закодируются в JSON.

**Comment by AzatGaliev** [comment]
ИМХО, view - не самое лучшее имя. Оно может пригодиться для других целей, имя довольно распространенное...

**Comment by VladimirShestakov** [comment]
А какое? А то уже всё сделал.. готовлю commit)

**Comment by AzatGaliev** [comment]
Ну тогда пофиг =)) Если будут неудобства - это сделать и потом недолго.

**Comment by VladimirShestakov** [comment]
Параметр `view` переименовал в `direct`
