### ISSUE TITLE
Создать виджет Add для добавления объекта

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#58]
Виджет добавления многофункциональный. 
1. Вначале отображается список часто добавляемых объектов для быстрого выбора. Данная функциональность предусматривается на будущее, когда будет сделана классификация. На первое время можно показывать пустой список или список из одного базового объекта Entity.
2. Кроме списка отображать кнопку "Другой..." для выбора любого объекта сайта. По нажатию на данную кнопку открывается обозреватель по всем объектам сайта. 

Выбранный из списка или обозревателя объекта добавляется прототипированием к объекту, который виджет Add (как любой виджет) должен отображать. На самом деле виджет Add его не отображает, а выполняет над ним действия - добавляет к нему новый объект. 

Виджет создать в пакете `admin_widgets` и добавить в список программ админки для всех объектов (как виджет Delete)

**Comment by AzatGaliev** [comment]
Ну и еще должна быть возможность создания объекта без прототипа.

**Comment by VladimirShestakov** [comment]
Вот он в списке должен быть, о нём сказано :) это Entity. Впрочем, возможность создания объекта без прототипа в админки не столь важная

**Comment by VladimirShestakov** [comment]
2fed7d210aad75d074c26eeb9b783de8c177caa7

Сделан без функции выбора любого объекта. Для примера предлагается один базовый объект, в будущем будут отображаться часто добавляемые.

Расширение возможностей будет отдельными задачами.
