### ISSUE TITLE
Установщик системы

### ISSUE THREAD

**Issue by AzatGaliev** [Boolive/Boolive#66]
Необходимо написать интерактивный установщик, который создаст необходимые таблицы в базах данных, обновит конфигурацию, проверит разрешения на запись.

**Comment by VladimirShestakov** [comment]
Стоит подождать, когда доделаю обновления с модулем данных, а то не угадаешь, какие таблицы создавать при установке :)

**Comment by AzatGaliev** [comment]
Ну я не тороплюсь, так, создал заранее =)

**Comment by VladimirShestakov** [comment]
Установщик должен работать без использования дампов базы данных. Всю информацию определять по файлам движка. В первую очередь из ".info" файлов в формате JSON. Они могут содержать всю информацию об объекте, в том числе и его подчиненных. Но кроме Info файлов необходимо учитывать php классы, являющиеся логикой объекта и любые другие файлы являющиеся значением объекта. Info файл может отсутствовать, тогда информацию об объекте следует выявить по классу или файлу-значению объекта. Например в phpDoc комментарии класса может содержаться вся необходимая информация, которая могла бы быть в info файле. А по расширению файла, например *.jpeg, *.js можно выявить прототип объекта.  Хотя можно всё упростить для установщика и обязать создавать Info файлы. Но было бы удобно, если для создания виджета достаточно было бы написать его класс, а в его комментариях дополнительную информацию.

Первым делом установщик находит все файлы и должен отличить файлы ядра от файлов данных. Файлы ядра в папке Boolive. В соответствии с информацией о наследовании классов / прототипирования объектов определяется порядок установки и наличие всех необходимых классов/файлов. У классов ядра поочередно запускается метод install, это позволит модульно проверить требования ядра и настроить их. Например, когда устанавливается модуль данных, то он запрашивает параметры базы данных и создаёт её. После установки ядра создаются объекты в базе данных.

**Comment by VladimirShestakov** [comment]
В классах `/Boolive` установщиком используются методы:
`systemRequirements()` - проверка системных требований для установки класса. Возвращает массив сообщений, если что-то не нравится классу.
`installPrepare()` - многомерный массив, описывающий форму для ввода данных. Используется, если классу нужно получить данные от пользователя, например, параметры доступа к базе.
`install($input)` - выполнение установки класса. В input введенные пользователем данные, если класс подготавливал форму. Используется для непосредственной установки/настройки класса.

В классах проекта такие методы не используются. После установки ядра выполняется создание объектов проекта - запись их в базу из .info файлов. В .info файлах должна содержаться исчерпывающая информация об объекте - его значение, прототип, порядковый номер и другие атрибуты. Неуказанные атрибуты принимают значение по умолчанию.

В файле `config.php` определена константа `IS_INSTALL`. Если она false, то запускается установщик системы. Установщик её сам меняет на true после успешной установки.
