### ISSUE TITLE
Поиск и установка объектов из файлов

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#67]
Находить в файловой системе информацию об объектах, которых нет в базе данных. Логика поиска как у установщика, разве что не надо устанавливать ядро, а только новые объекты данных.

В админке нужно создать виджет-программу "Импорт", которую можно запустить для любого объекта и в рамках его структуру произвести поиск неустановленных подчиненных. Если программа запускается для корневого объекта, то определяются обновления для всех объектов. Обновления - это неустановленные подчиненные объекты.

**Comment by AzatGaliev** [comment]
Начал делать.

**Comment by AzatGaliev** [comment]
Появилось несколько вопросов, попробую изложить. Все по client-side. Что за предки и child'ы у виджета? Сорри, вообще не понимаю. Не мог бы изложить?

**Comment by VladimirShestakov** [comment]
jquery ui плагины (виджеты) автоматом приделываются к тегам с атрибутами data-p  (data-plugin). Имя плагина берется из атрибута. Получается, что плагины client-side тоже выстраиваются в иерархию как и на server-side. Но если смотреть по DOM, то в подчинении или в родителе часто будут DOM элементы без плагинов. 
Когда создаётся экземпляр плагина, генерируется событие, которое распространяется как и любое js событие вверх по DOM родителям. Элементы с плагином реагируют на это событие и фиксируют, какой именно плагин является непосредственным подчиненным. Таким образом в подчиненных у нас экземпляры плагинов, а не DOM элементы. Нужны они, чтобы взаимодействовать между собой.

Можно было бы обойтись стандартными событиями для взаимодействия плагинов, вызывая события через .trigger() Но этого оказалось недостаточно, так как событие всегда распространяется вверх от подчиненного к родителям, а потребовалось и обратное направление.  

Например в плагине `ObjectItem` фиксируется клик мышки, что означает выделение объекта или вход в него. Делается вызов действия у родителей `callParents('setState', .....)` - типа просим изменить состояние, но не знаем кто его менять будет. (ранее этот метод был назван `before`).. Дело доходит до плагина `Admin`, у него срабатывает метод `call_setState()` (ранее `before_setState()`). В `Admin` меняется состояние, строка в браузере (история). А далее `Admin` сообщает об изменении состояния всем своим подчиненным - делается вызов `callChildren('setState',...);` (раньше было `after('setState',..)`) на него отреагируют меню `Breadcrumbs`, `ProgramsMenu`, `Programs` и все другие. При этом между собой они не связаны, да и находятся в разных ветках DOM. Смена состояние может быть инициировано из `Breadcrumbs` и оно также везде учтётся.

Этот способ взаимодействия ещё полируется, но находит удачное применении во всём, например в редакторе текста нашёл)

**Comment by VladimirShestakov** [comment]
Для твоей задачи с этим возится не надо. Плагин нужно написать только для ajax взаимодействия - отправлять на сервер подтверждение экспорта/импорта. И, наверно, в виду продолжительности операции экпорта/импорта на сервере, выполнять её частями, а с клиента циклом посылать команды продолжения.

Вот шаблон ui виджета

``` js
/**
 * WidgetName
 * Query UI widget
 */
(function($) {
    $.widget("boolive.WidgetName", $.boolive.AjaxWidget, {
        // uri отображаемого объекта
        _object: '',

        _create: function() {
            $.boolive.AjaxWidget.prototype._create.call(this);
            var self = this;
            // uri объекта
            self._object = this.element.attr('data-o'); //из атрибута берем
         });
})(jQuery);
```

**Comment by AzatGaliev** [comment]
А может быть, в самом PHP убирать время timeout'а, чтобы скрипт мог (теоритически) работать бесконечно?

**Comment by VladimirShestakov** [comment]
Без timeout только в консольном режиме (CLI). Через админку требуется работа на любом хостинге, где timeout обычно 30 сек и его не поменять.

**Comment by VladimirShestakov** [comment]
#90 - связанная задача

**Comment by VladimirShestakov** [comment]
Поиск выполняется автоматически при просмотре объекта в админке. Новые объекты добавляются в базу с атрибутом `diff = Entity::DIFF_ADD`. Для их окончательной установки нужно только обнулить атрибут `diff`. Для существующих объектов проверяются различия в атрибутах. Если различия найдены, то `diff = Entity::DIFF_CHANGE`. Для окончательной установки нужно будет прочесть info файл и присвоить новые атрибуты объекту.

Остаётся сделать программу, которая будет устанавливать (сохранять) найденные изменения. С помощью этой же программы будут устанавливаться изменения от прототипа.
