### ISSUE TITLE
Дамп данных в файлы

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#68]
Вместо дампов базы данных в виде sql файлов при установке системы и отдельно модулей используется информация из Info файлов.  После продолжительной работы движка, большинство данных будут только в базе данных. В рамках разработки движка или экспорта модуля необходимо автоматизировать экспорт данных в info файлы. 

В админке создать виджет-программу "Экпорт" или с другим названием. Задача которой - экспортировать текущий объект с его подчиненным в info файлы.

**Comment by AzatGaliev** [comment]
Еще как вариант - виджет, который будет экспортировать абсолютно все объекты. Хотя, твой вариант более гибкий =)

**Comment by VladimirShestakov** [comment]
Если текущий объект корневой, то экспортируются все объекты.

**Comment by VladimirShestakov** [comment]
Ещё сразу можно учесть оптимальное создание info файлов. То есть группировать в одном Info файле информацию о нескольких подчиненных, а не создавать на каждый по файлу. Например заголовки, описания..

**Comment by AzatGaliev** [comment]
А какая будет логика, если есть и _.info файл, и информация об объекте в
*.info файле [пра_]родителя?

**Comment by VladimirShestakov** [comment]
Отельный файл по идеи должен переопределить инфо родителя, так как сначала родителя будем пытаться создать. Тут вопрос оптимизации, чтобы лишние файлы не создавать.

**Comment by VladimirShestakov** [comment]
Добавлены методы `Entity::export()` и `Entity::exportedProperties()`. Первым выполняется экспортирование объекта в info файл. Второй возвращает названия свойств, которые нужно экспортировать в один файл вместе с объектом. По умолчанию возвращаются в массиве названия title и description. Если вместо массива возвращать `true` то будут экспортироваться все свойства объекта. Такое применяется для объекта стиля.
