### ISSUE TITLE
Выделение нескольких объектов в обозревателе админки

### ISSUE THREAD

**Issue by paulinep** [Boolive/Boolive#72]
Было бы удобно выделять несколько объектов для например удаления или копирования. Про добавление внутрь их не говорю, т.к. наверное очень дорогая операция да и редкая

**Comment by VladimirShestakov** [comment]
Можно выделить несколько объектов и удалить их. Другие программы пока не могут работать с несколькими объектами.

Множественное выделение также учитывается при выборе новых объектов - сколько выделить, столько будет создано. Это практично, если нужно сразу добавить несколько объектов, но нужно додумывать интерфейс, чтобы можно было добавить разом несколько одинаковых объектов (когда выделен один, но его нужно добавить несколько раз)

**Comment by VladimirShestakov** [comment]
При выборе программы (например, удаления) для множества объектов в BreadcrumbsMenu будет отображаться путь к первому объекту из выделенных. Нужно додумывать, что именно в таких случаях показывать в  BreadcrumbsMenu.
