### ISSUE TITLE
Копирование объектов в обозревателе

### ISSUE THREAD

**Issue by paulinep** [Boolive/Boolive#73]
Для ускорения создания большого количества однотипных объектов было бы удобно реализовать копирование по образцу уже созданного.

**Comment by AzatGaliev** [comment]
А разве это уже не заложено в модель данных? Все же на прототипах? Или ты имеешь в виду копирование без последующего привязывания к объекту?

**Comment by VladimirShestakov** [comment]
Копирование в прямом смысле - создаётся новый объект с таким же прототипом, значением, признаками и подчиненными как у копируемого объекта.  При этом никакой связи с копируемым объектом не создаётся.
