### ISSUE TITLE
Создать рамку для масштабирования картинок в редакторе текста

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#74]
Рамка появляется поверх картинки, если картинка выделена. При отмене выделения рамка удаляется. 

Представляет собой стандартную рамку как во многих редакторах графических - по углам и по бокам маленькие квадратики, за которые можно тянуть мышкой и тем самым изменять размеры рамки и самой картинки. От квадратика зависит, что изменяется, высоты, ширина или всё сразу. Но размеры всегда изменяются пропорционально. Как дополнение можно сделать непропорциональное изменение размера, если зажата клавиша `ctrl`

DOM элемент рамки не должен оказываться в области текста редактора. Скорее всего с абсолютным позиционированием в body.

**Comment by AzatGaliev** [comment]
Мне кажется, поведение с Control не совсем интуитивно. Обычно, если тянуть с Shift, картинка изменяется пропорционально, а если просто мышкой - непропорционально.

**Comment by paulinep** [comment]
Думаю, что не принципиально какая кнопка...Shift или Ctrl все равно для большинства они обе неочевидны без подсказки. Нужно будет продумать как вывести подсказку.

**Comment by VladimirShestakov** [comment]
Про неочевидность дополнительной функции согласен. Поэтому и подумали по умолчанию пропорционально масштабировать, так как этот режим не искажает картинку. А для без пропорции масштабировать можно применить кнопку `shift`. Тогда при `ctrl` можно будет дополнительно сделать масштабирование без прилипания к сетке (округления размеров), соответственно без `ctrl` с прилипанием. Это как в линейке.

**Comment by AzatGaliev** [comment]
Не знаю, не знаю. Лично я сам знаю эту "неочевидность". И многие мои знакомые, в основном - продвинутые пользователи. Но мне кажется, что не так уж много домохоязек будет использовать нашу CMS.

**Comment by VladimirShestakov** [comment]
Поведение по `shift` можно поменять. Посмотрим в реальном применении, хорошо? )

**Comment by Ishodnikov** [comment]
По умолчанию, однозначно, пропорционально нужно масштабировать! Потому как непропорциональное масштабирование куда реже используется.

**Comment by AzatGaliev** [comment]
Ну окей, как хотите. Просто более стандартное поведение, ИМХО, лучше. Все везде стандартно, как везде - у юзера нет проблем.

**Comment by paulinep** [comment]
Есть еще небольшое уточнение. Вот если двигать за угловые, то я сделала пропорционально - все логично. А вот если тянем за боковые то пропорциональное изменение уже как то не вяжется. Вроде как изменяю только высоту, а оно зачем-то еще и ширину само меняет. Может безо всяких кнопок - за средние контролы пусть непропорционально меняется. Так логичнее.
