### ISSUE TITLE
Постраничное отображение объектов в обозревателе админки?

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#77]
Нужно ли в обще постраничное отображение в обозревателе админки, если объектов очень много?

**Comment by Ishodnikov** [comment]
Думаю да, взять, например, комментарии к статье. Они же будут тоже как объекты, правильно? А выводить из все на одной странице смысла нет. Сделать фильтр выводить по Все, по 10,100,1000)
