### ISSUE TITLE
Создать программу "Восстановить" в админке

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#80]
Создать программу (виджет) "Восстановить" в админке для восстановления удаленных объектов. Удаленные объекты имеют признак `is_delete`. Их восстановление - это смена признака `is_delete` на false.

Программа должна отображаться в меню (работать) если **все выделенные** объекты имеют признак `is_delete`. Функционально похожа на программу удаления.

**Comment by paulinep** [comment]
Вот коммит 97df09a. Но там есть еще одна небольшая недоделка. Сейчас очень трудно заставить ProgramsMenu  менять свой список сразу после выполнения какой-либо программы, это особенно актуально с удаленными объектами, т.к. 2 раза удалять их бессмысленно и хотелось бы, чтобы список для удаленного объекта сразу содержал кнопку восстановить, а не только при переходе на другой объект обновлялся.
