### ISSUE TITLE
Формат .info файлов

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#85]
В `.info` файле записывается вся информация об объекте, которая может быть импортирована в базу данных. И, наоборот, из базы данных в этот файл. 
`.info` файл содержит данные в JSON формате. В нём прописываются атрибуты объекта. Обязательных атрибутов нет. Имя и родитель объекта определяется по пути на файл. Остальные атрибуты задаются по умолчанию, если не указаны. Если не указан прототип `proto`, то у объекта нет прототипа.

Кроме атрибутов в этом же файле могут быть прописаны подчиненные объекты (если нет смысла в создании отдельных для них `.info` файлов в подпапках).

``` json
{
    "proto": "/Library/basic/SomeObject",
    "order": 10,
    "value": "xxxxx",
    "children": { //список подчиненных. Ключи - имена подчиненных объектов.
         "title": {
              "value": "Заголовок объекта"
          },
          "description": {
              "value": "Описание объекта",
              "order": 2
          }
     }
}
```

Можно учесть сокращенный вариант

``` json
{
    "proto": "/Library/basic/SomeObject",
    "order": 10,
    "value": "xxxxx",
    "children": {  
         "title": "Заголовок объекта",
          "description": {
              "value": "Описание объекта",
              "order": 2
          }
     }
}
```

Или ещё более сокращенный, который сейчас везде применяется. Но этот вариант не всегда подойдет, если имя подчиненного объекта совпадает с названием одного из атрибутов объекта. 

``` json
{
    "proto": "/Library/basic/SomeObject",
    "order": 10,
    "value": "xxxxx",
    "title": "Заголовок объекта",  //подчиненный и его значение
    "description": "Описание объекта" //подчиненный и его значение
}
```

**Comment by AzatGaliev** [comment]
Окей, делаю импорт по этому соглашению.

**Comment by VladimirShestakov** [comment]
Для экспорта самый сокращенный не применяй ввиду возможных конфликтов. Сначала можешь предполагать, что все атрибуты объекта указаны, а потом улучшать алгоритм, чтобы многие из них автоматом определялись, если не указаны. Например, имя и родитель по файлу. По наличию php файла делать признак своего класса, определять, что значением является файл от того что есть файл в папке (например картинка). 

Если зайти ещё дальше, то дополнительную информацию об объекте - его `title`, `description` и даже `proto` можно определять из php файла. Но это надо парсить php файл. У меня есть алгоритм )
