### ISSUE TITLE
Куда добавлять объект?

### ISSUE THREAD

**Issue by VladimirShestakov** [Boolive/Boolive#86]
Новые объекты сейчас добавляются в выделенный объект (становятся его свойством). Таким образом, если в обозревателе ничто не выделено, то новый объект добавится в конец списка. А если выделен некий объект, то уже внутрь него!

Предлагаю поменять поведение. Добавлять всегда в отображаемый список, а не в выделенный объект. Если есть выделенный объект, то новый добавляется после него (или перед?).

**Comment by Ishodnikov** [comment]
Думаю после, в иерархическом виде, как свойство.

**Comment by VladimirShestakov** [comment]
Хм, тогда программе добавления нужно знать способ отображения объектов в обозревателе.
